# Created using wingetcreate 0.4.0.3
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json

PackageIdentifier: Aerosoft.AerosoftLauncher
PackageVersion: 1.2.0.5
InstallerSwitches:
  Silent: Silent
  SilentWithProgress: SilentWithProgress
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://launcher.aerosoft.com/downloads/launcher/AS_AEROSOFT-LAUNCHER_V1205.exe
  InstallerSha256: 94C84F2D8DFB33304FE0A225A5321E166AEF4B2B25305AE1AF86B169B758A03A
ManifestType: installer
ManifestVersion: 1.0.0

